name: Verify

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Verify Python version
        run: |
          python --version

      - name: Create and activate virtualenv
        run: |
          cd vitivinicultura-api
          make venv

      - name: Install dependencies
        run: |
          cd vitivinicultura-api
          make install

      - name: Run lint
        run: |
          cd vitivinicultura-api
          make lint
