name: Verify and Deploy

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PROJECT_FOLDER: vitivinicultura-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Verify Python version
        run: |
          python --version

      - name: Create and activate virtualenv
        run: |
          cd $PROJECT_FOLDER
          make venv

      - name: Install dependencies
        run: |
          cd $PROJECT_FOLDER
          make install

      - name: Run lint
        run: |
          cd $PROJECT_FOLDER
          make lint

  docker-build:
    runs-on: ubuntu-latest
    needs: lint
    env:
      DOCKER_IMAGE_NAME: fiap/vitiviniculture-api
      PROJECT_FOLDER: vitivinicultura-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd $PROJECT_FOLDER
          docker build -t $DOCKER_IMAGE_NAME .

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json"
